# Generated by Django 4.0.4 on 2022-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_profile_address_profile_mobile_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.', max_length=100),
        ),
    ]
