# Generated by Django 4.0.4 on 2022-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Uzbekistan, Tashkent, Mirabad, Nukus street', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default='+99890 9999999 (Default)', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+99871 1234567 (Default)', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
